language: cpp
dist: xenial
before_script:
- sudo apt-add-repository -y "deb http://archive.ubuntu.com/ubuntu xenial main universe"
- sudo apt-get install -y libgtest-dev build-essential cmake
- pushd /usr/src/gtest
- sudo cmake .
- sudo cmake --build . -- -j "`nproc`"
- popd
script:
- cmake .
- cmake --build . -- -j "`nproc`"
- cmake --build . --target test -- -j "`nproc`"
- cmake --build . --target package -- -j "`nproc`"
deploy:
  provider: script
  skip_cleanup: true
  debug: on
  script:
    - curl -T "origin-prog_0.0.${TRAVIS_BUILD_NUMBER}_amd64.deb" -u sergmusor:"$BINTRAY_API_KEY" "https://api.bintray.com/content/sergmusor/starting-point/origin/0.0.${TRAVIS_BUILD_NUMBER}/pool/main/o/origin/origin-prog_0.0.${TRAVIS_BUILD_NUMBER}_amd64.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1" -T "origin-lib_0.0.${TRAVIS_BUILD_NUMBER}_amd64.deb" -u sergmusor:"$BINTRAY_API_KEY" "https://api.bintray.com/content/sergmusor/starting-point/origin/0.0.${TRAVIS_BUILD_NUMBER}/pool/main/o/origin/origin-lib_0.0.${TRAVIS_BUILD_NUMBER}_amd64.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
